---
# ==============================================================
# Blockchain Node Deployment – Reset & Redeploy (with forced image pull)
# ==============================================================

# 🧹 Cleanup Section
- name: Stop and remove all existing containers and volumes
  shell: |
    docker compose -f /opt/blockchain-node/docker-compose.yml down -v --remove-orphans || true
    docker system prune -af || true
  args:
    chdir: /opt/blockchain-node
  ignore_errors: true
  become: true

# 🧱 Directory setup
- name: Remove old blockchain-node directory
  file:
    path: /opt/blockchain-node
    state: absent
  become: true

- name: Recreate blockchain-node directory
  file:
    path: /opt/blockchain-node
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: true

# 🧩 Copy docker-compose template
- name: Copy docker-compose template
  template:
    src: docker-compose.yml.j2
    dest: /opt/blockchain-node/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
  become: true

# 🔄 Pull the specific (tagged) image 
- name: Force pull the latest version of the blockchain image
  shell: docker pull {{ docker_image }}
  become: true

# 🚀 Deploy container
- name: Deploy blockchain container
  shell: |
    docker compose -f /opt/blockchain-node/docker-compose.yml up -d
  args:
    chdir: /opt/blockchain-node
  become: true

# ✅ Verify
- name: Check running containers
  shell: >
    docker ps --format "table {{ '{{' }}.Names{{ '}}' }}\t{{ '{{' }}.Image{{ '}}' }}\t{{ '{{' }}.Status{{ '}}' }}\t{{ '{{' }}.Ports{{ '}}' }}"
  register: container_status
  become: true

- name: Show container status
  debug:
    msg: "{{ container_status.stdout_lines }}"
