---
- name: Ensure Docker is installed
  apt:
    name: docker.io
    state: present
    update_cache: yes
  become: true

- name: Ensure Docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Copy docker-compose template
  template:
    src: docker-compose.yml.j2
    dest: /opt/blockchain-node/docker-compose.yml
    owner: root
    group: root
    mode: 0644
  become: true

- name: Deploy blockchain container
  shell: |
    docker compose -f /opt/blockchain-node/docker-compose.yml up -d
  args:
    chdir: /opt/blockchain-node/
  become: true
