---
- name: Stop and remove all existing containers for blockchain node
  shell: |
    docker compose -f /opt/blockchain-node/docker-compose.yml down -v --remove-orphans || true
    docker system prune -af || true
  args:
    chdir: /opt/blockchain-node
  become: true
  ignore_errors: true

- name: Ensure required packages for Docker repo are installed
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  become: true

- name: Add Docker GPG key (Debian-safe)
  ansible.builtin.shell: |
    set -e
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor --yes --batch -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    executable: /bin/bash
  become: true


- name: Add Docker repository for Debian (bookworm)
  ansible.builtin.shell: |
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
      https://download.docker.com/linux/debian bookworm stable" \
      | tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    executable: /bin/bash
  become: true

- name: Update apt cache
  apt:
    update_cache: yes
  become: true

- name: Install Docker Engine and Docker Compose plugin
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true

- name: Ensure Docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Ensure /opt/blockchain-node directory exists
  file:
    path: /opt/blockchain-node
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: true

- name: Copy docker-compose template
  template:
    src: docker-compose.yml.j2
    dest: /opt/blockchain-node/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Deploy blockchain container
  shell: |
    docker compose -f /opt/blockchain-node/docker-compose.yml up -d
  args:
    chdir: /opt/blockchain-node
  become: true
